"use client"

import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { DataChart } from "@/components/data-chart"
import { ShoppingCart, TrendingUp, Award, ArrowUpRight, ArrowDownRight } from "lucide-react"
import { ChartConfig } from "@/components/ui/chart"

const topProductsData = [
    { name: "Premium Widget", sales: 1250, revenue: 37500, trend: "+12%", status: "High Growth" },
    { name: "Advanced Contraption", sales: 450, revenue: 45000, trend: "+8%", status: "Premium" },
    { name: "Standard Gadget", sales: 980, revenue: 19600, trend: "-3%", status: "Stable" },
    { name: "Simple Doohickey", sales: 1100, revenue: 5500, trend: "+24%", status: "Volume Leader" },
    { name: "Basic Thingamajig", sales: 750, revenue: 7500, trend: "+5%", status: "Stable" },
]

const chartConfig = {
    revenue: { label: "Revenue (₦)", color: "hsl(var(--primary))" },
} satisfies ChartConfig

export default function TopSellingPage() {
    return (
        <div className="flex flex-col gap-8 pb-12">
            <div>
                <h1 className="font-headline text-3xl font-bold tracking-tight">Top-Selling Products & Services</h1>
                <p className="text-muted-foreground mt-1">
                    Identify your most popular offerings to optimize your sales and marketing efforts.
                </p>
            </div>

            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                <Card className="hover:shadow-md transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Best Selling (Volume)</CardTitle>
                        <div className="bg-primary/10 p-2 rounded-lg">
                            <ShoppingCart className="h-4 w-4 text-primary" />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold font-headline">Premium Widget</div>
                        <p className="text-xs text-muted-foreground mt-1">1,250 units sold this month</p>
                    </CardContent>
                </Card>
                <Card className="hover:shadow-md transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Highest Revenue</CardTitle>
                        <div className="bg-emerald-500/10 p-2 rounded-lg">
                            <TrendingUp className="h-4 w-4 text-emerald-600" />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold font-headline">₦45,000</div>
                        <p className="text-xs text-muted-foreground mt-1">Advanced Contraption</p>
                    </CardContent>
                </Card>
                <Card className="hover:shadow-md transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Top Emerging</CardTitle>
                        <div className="bg-amber-500/10 p-2 rounded-lg">
                            <Award className="h-4 w-4 text-amber-600" />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold font-headline">Simple Doohickey</div>
                        <p className="text-xs text-green-600 flex items-center gap-1 font-medium mt-1">
                            <ArrowUpRight className="h-3 w-3" /> +24% growth
                        </p>
                    </CardContent>
                </Card>
            </div>

            <div className="grid gap-6 lg:grid-cols-7">
                <Card className="lg:col-span-4">
                    <CardHeader>
                        <CardTitle className="font-headline">Revenue by Product</CardTitle>
                        <CardDescription>Comparison of revenue generated by top 5 products.</CardDescription>
                    </CardHeader>
                    <CardContent className="pt-2">
                         <DataChart 
                            type="bar" 
                            data={topProductsData} 
                            config={chartConfig} 
                            dataKeys={['revenue']} 
                            index="name" 
                        />
                    </CardContent>
                </Card>

                <Card className="lg:col-span-3">
                    <CardHeader>
                        <CardTitle className="font-headline">Sales Velocity</CardTitle>
                        <CardDescription>Monthly unit sales trend.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div className="rounded-md border">
                            <Table>
                                <TableHeader>
                                    <TableRow>
                                        <TableHead>Product</TableHead>
                                        <TableHead className="text-right">Sales</TableHead>
                                        <TableHead className="text-right">Trend</TableHead>
                                    </TableRow>
                                </TableHeader>
                                <TableBody>
                                    {topProductsData.map((item) => (
                                        <TableRow key={item.name}>
                                            <TableCell className="font-medium">{item.name}</TableCell>
                                            <TableCell className="text-right">{item.sales.toLocaleString()}</TableCell>
                                            <TableCell className="text-right">
                                                <span className={item.trend.startsWith('+') ? "text-green-600 font-medium" : "text-red-600 font-medium"}>
                                                    {item.trend}
                                                </span>
                                            </TableCell>
                                        </TableRow>
                                    ))}
                                </TableBody>
                            </Table>
                        </div>
                    </CardContent>
                </Card>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle className="font-headline">Detailed Offering Report</CardTitle>
                    <CardDescription>A complete look at product and service rankings by performance.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="rounded-md border">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Product/Service Name</TableHead>
                                    <TableHead>Category</TableHead>
                                    <TableHead className="text-right">Units Sold</TableHead>
                                    <TableHead className="text-right">Total Revenue</TableHead>
                                    <TableHead className="text-center">Market Status</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {topProductsData.map((item) => (
                                    <TableRow key={item.name}>
                                        <TableCell className="font-bold">{item.name}</TableCell>
                                        <TableCell>Inventory Item</TableCell>
                                        <TableCell className="text-right">{item.sales.toLocaleString()}</TableCell>
                                        <TableCell className="text-right font-mono font-bold">₦{item.revenue.toLocaleString()}</TableCell>
                                        <TableCell className="text-center">
                                            <Badge 
                                                variant={item.status === "High Growth" ? "default" : "secondary"}
                                                className={item.status === "High Growth" ? "bg-primary/10 text-primary hover:bg-primary/20" : ""}
                                            >
                                                {item.status}
                                            </Badge>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </div>
                </CardContent>
            </Card>
        </div>
    )
}
