
"use client"

import * as React from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { DataChart } from "@/components/data-chart"
import { 
    ShoppingCart, 
    TrendingUp, 
    ArrowUpRight, 
    ArrowDownRight, 
    Loader2,
    Package
} from "lucide-react"
import { ChartConfig } from "@/components/ui/chart"
import { cn } from "@/lib/utils"
import { getProductPerformanceAction } from "@/app/reports/actions"

const chartConfig = {
    total_revenue: { label: "Revenue (₦)", color: "hsl(var(--primary))" },
} satisfies ChartConfig

export default function TopSellingPage() {
    const [loading, setLoading] = React.useState(true);
    const [data, setData] = React.useState<any[]>([]);

    React.useEffect(() => {
        const fetch = async () => {
            const res = await getProductPerformanceAction();
            if (res.success) setData(res.data);
            setLoading(false);
        };
        fetch();
    }, []);

    if (loading) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="h-10 w-10 animate-spin text-primary" /></div>;

    const bestSeller = data[0];

    return (
        <div className="flex flex-col gap-8 pb-12">
            <div>
                <h1 className="font-headline text-3xl font-bold tracking-tight">Top-Selling Products</h1>
                <p className="text-muted-foreground mt-1">
                    Performance analytics derived from your relational sales ledger.
                </p>
            </div>

            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                <Card className="hover:shadow-md transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Best Selling (Volume)</CardTitle>
                        <div className="bg-primary/10 p-2 rounded-lg">
                            <ShoppingCart className="h-4 w-4 text-primary" />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold font-headline">{bestSeller?.product_name || 'N/A'}</div>
                        <p className="text-xs text-muted-foreground mt-1">{bestSeller?.units_sold || 0} units sold to date</p>
                    </CardContent>
                </Card>
                <Card className="hover:shadow-md transition-shadow">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Top Revenue Generator</CardTitle>
                        <div className="bg-emerald-500/10 p-2 rounded-lg">
                            <TrendingUp className="h-4 w-4 text-emerald-600" />
                        </div>
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold font-headline">₦{Number(bestSeller?.total_revenue || 0).toLocaleString()}</div>
                        <p className="text-xs text-muted-foreground mt-1">{bestSeller?.product_name || 'N/A'}</p>
                    </CardContent>
                </Card>
            </div>

            <div className="grid gap-6 lg:grid-cols-7">
                <Card className="lg:col-span-4">
                    <CardHeader>
                        <CardTitle className="font-headline">Revenue by Product</CardTitle>
                        <CardDescription>Comparison of revenue generated by top offerings.</CardDescription>
                    </CardHeader>
                    <CardContent className="pt-2">
                         <DataChart 
                            type="bar" 
                            data={data} 
                            config={chartConfig} 
                            dataKeys={['total_revenue']} 
                            index="product_name" 
                        />
                    </CardContent>
                </Card>

                <Card className="lg:col-span-3">
                    <CardHeader>
                        <CardTitle className="font-headline">Sales Velocity</CardTitle>
                        <CardDescription>All-time unit sales trend.</CardDescription>
                    </CardHeader>
                    <CardContent className="p-0">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead className="pl-6">Product</TableHead>
                                    <TableHead className="text-right pr-6">Sales</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {data.map((item) => (
                                    <TableRow key={item.sku}>
                                        <TableCell className="pl-6">
                                            <p className="font-bold text-sm">{item.product_name}</p>
                                            <p className="text-[10px] text-muted-foreground uppercase">{item.sku}</p>
                                        </TableCell>
                                        <TableCell className="text-right pr-6 font-mono font-bold">
                                            {item.units_sold.toLocaleString()}
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    </CardContent>
                </Card>
            </div>
        </div>
    )
}
